#!/bin/bash
#set -e

echo "Packaging"

source $(dirname $0)/version
source $(dirname $0)/images

cd $(dirname $0)/..

DIST=$(pwd)/dist/artifacts

echo "Step 1"
pushd images/output
build_all "$@"
mkdir -p ${DIST}
echo "Step 1.5"
copy_all ${DIST} "$@"
popd

echo "Step 2"
mkdir -p ./build
ID=$(docker create ${REPO}/k3os-package:${TAG})
docker cp ${ID}:/output/k3os ./build/
echo "Removing $ID"
docker_rm $ID

echo "Step 3"
docker build \
  --build-arg ARCH=${ARCH} \
  --build-arg REPO=${REPO} \
  --build-arg TAG=${TAG} \
  --build-arg VERSION=${VERSION} \
  --file package/Dockerfile \
  --tag ${REPO}/k3os:${TAG} \
  --tag ${REPO}/k3os:latest \
.
echo "Step 4"
docker image save --output ./dist/images.tar \
  ${REPO}/k3os:${TAG} \
  ${REPO}/k3os:latest
echo ${REPO}/k3os:${TAG} > ./dist/images.txt
echo Built ${REPO}/k3os:${TAG}
